dataset: coco
target_batch_size: 256 
batch_size: 256
epochs: 100

opt: Muon
opt_kwargs:
  lr: 1.0e-3
  eps: 1.0e-15
  betas: [0.9, 0.95]
  weight_decay: 0.1

scheduler: Staircase
scheduler_kwargs:
  ramp_down_steps: 1000
  breakpoints: [20000, 40000, 80000]
  lr_values: [5.0e-4, 1.0e-4, 5.0e-5]

checkpoint_root_dir: checkpoints

log_interval: 1
sample_interval: 500
save_interval: 20000
val_interval: 5000
resume: false
resume_path: checkpoints/mars_20k

n_samples: 16
sample_prompts:
  - golden retriever
  - tabby cat
  - school bus
  - tennis ball
  - acoustic guitar
  - monarch butterfly
  - great white shark
  - bald eagle
  - red panda
  - pineapple
  - fire truck
  - grand piano
  - mountain bike
  - polar bear
  - peacock
  - zebra

val_batch_mult: 2
